---
kind: pipeline
type: docker
name: docker-build

steps:
  - name: docker
    image: plugins/kaniko:1.5.1-linux-amd64-kaniko1.8.1
    settings:
      repo: 15cm/mastodon-twitter-poster
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - main
  event:
    - push
    - custom
    - tag
