language: ruby
cache:
    bundler: true
    directories:
        - vendor/assets/bower_components
        - node_modules
rvm:
  - 2.4.1
bundler_args: --without production
addons:
    postgresql: "9.6"
