# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 629a33f248a7b17a9ce28ea90a713d082de9547a4a5df4102a425604093b0f3fa2f9c5ecc735670792a0eeed916022d7e7ddc98af7ebf2efd859b71addbe1b0c

test:
  secret_key_base: f8c10d7f857ec430cf1dfa867f5aedcf2c30332e876bcaa527d61b353c333d4c12901e9c746d0fdba4eb4648ed3dd55562f365ff32e9e0dd6eb3dadeae7968b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
