name: Pronto
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "Gemfile"
      - "Rakefile"
      - "**/*.rb"
      - "**/*.ru"
      - "bin/*"
jobs:
  pronto:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 150
      - run: git fetch origin main --depth=20
      - uses: renatolond/pronto-ruby@use_head_commit
        with:
          target: origin/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
